### ISSUE TITLE
UND_ERR_CONNECT_TIMEOUT when running astro build

### ISSUE THREAD

**Issue by perryrh0dan** [natemoo-re/astro-icon#108]
First of all, thank you for this great libray and your efforts. 

Unfortunately, I get a lot of 'UND_ERR_CONNECT_TIMEOUT' errors when building my application, which leads to a failed build in the end. Do you have any idea how to prevent this? Is there any rate limit on api.astroicon.dev?

**Comment by stramel** [comment]
@perryrh0dan I'm not sure where this would be coming from. Can you explain a bit more about your build process/environment and any details on the application? 

If you could throw together a reproducible issue, that would go a long ways to getting this resolved.

**Comment by perryrh0dan** [comment]
I will try to reproduce the problem in a separate repository.

**Comment by marcosmartini** [comment]
Hey there, I'm getting a broken build and errors in dev if I use Material design icons like:

`<Icon role="img" name="mdi:github" width="24" title="Github" />`

**Comment by marcosmartini** [comment]
Hey @perryrh0dan, I can confirm my problem above has been fixed in both `0.8.0` and `0.8.1` — but not sure if it fixes for you, worth giving a shot. Cheers.

**Comment by stramel** [comment]
I'm going to close this as I have no way to reproduce and it sounds like it may have been an issue with the server.
