### ISSUE TITLE
SpriteSheet doesn't detect icons used in components

### ISSUE THREAD

**Issue by Princesseuh** [natemoo-re/astro-icon#11]
## Problem
It seems like the tracking system used by SpriteSheet to get a list of your used icons doesn't detect icons that are used in components. This worked before this tracking system was added

## Exemple use case
I have a BaseLayout.astro file with `<SpriteSheet/>` at its end, that `BaseLayout.astro` has a `<Socials>` component that includes icons and it causes the following error: `[astro-icon] <SpriteSheet> should be the very last child of the page's <body>!
Is it currently placed before any <Sprite> components?`

A solution could be to put `<SpriteSheet/>` in that `<Socials />` component, however this is not possible as this `<Socials>` components is used multiple times throughout the Layout (once in the Header, once in the Footer, which incidentally are also separate components)

## Potential solutions

If it isn't possible to make it detect icons used in components (I don't think it is from my exploration of building Astro components but I could be proved wrong?), it'd be great to at least be able to manually supply a list of icons to SpriteSheet to include 

## Minimal repro
https://stackblitz.com/edit/github-c5ox6n

**Comment by natemoo-re** [comment]
Thank you for opening an issue! You're totally correct, I'll try to take a look at this soon!

**Comment by natemoo-re** [comment]
This was an interesting challenge to fix!

In some situations it worked, in others it didn't. Astro components are `async` and children are rendered in parallel, so if `SpriteSheet` was a sibling of any components that contained `Sprite`, it would resolve before the component `Sprite` did.

To fix this, I've deprecated `SpriteSheet` in [v0.5.0](https://github.com/natemoo-re/astro-icon/blob/main/packages/core/CHANGELOG.md#050). Instead, you should use the `Sprite.Provider` component to wrap your content. This removes the parallelism footgun.
