### ISSUE TITLE
Any possible integration with antfu/icones

### ISSUE THREAD

**Issue by jjaimealeman** [natemoo-re/astro-icon#110]
https://github.com/antfu/icones

I've been using this awesome setup in various Vue projects.

It seems them both use iconify for the SVG icons.

**Comment by stramel** [comment]
Icones uses Iconify as the source for all the icons. How would you imagine we use Icones with Astro Icon? 

Antfu already has unplugin-icons which uses virtual module paths to embed icons. This can be used instead of astro Icon.

**Comment by jjaimealeman** [comment]
My apologies. I'm not certain how all this works.

But I see you've already done a PR for this https://github.com/natemoo-re/astro-icon/pull/105 👍

**Comment by stramel** [comment]
@jjaimealeman No worries! We utilize Iconify as our source for icons just like the Icones website and `unplugin-icons` plugin does. 

We have support on `unplugin-icons` for Astro components and this component lets you use the icons directly using a different setup. I'll go ahead and close this as it looks like you were looking for icons that were missing.
