### ISSUE TITLE
Fails to load some icons

### ISSUE THREAD

**Issue by ShayanTheNerd** [natemoo-re/astro-icon#119]
Hi and thanks for this good plugin

I was developing this Astro project in which I needed a stack-like icon. So I head over to https://icones.js.org/collection/all (BTW, big thanks to @antfu) and found `heroicons-outline:rectangle-stack`, But when I tried to use it alongside the other icons using the `<Icon />` component, it didn't show up. I inspected the icon and found _Failed to load "heroicons-outline:rectangle-stack"!_ title in the SVG tag,  as if the name of the icon was wrong or something. I also tested some other icons such as `heroicons-outline:circle-stack` or `material-symbols:full-stacked-bar-chart` and the same happened. Something seems to be wrong with the word _stack_. Anyway, I fixed my problem using conditional rendering since I only needed this one problematic icon, but hope you solve this issue soon.

**Comment by stramel** [comment]
Hi, thanks for taking the time to file the issue! I believe this is the same issue as #29. v1 will fix this once we release it. 

I'm going to mark this as a duplicate and close it.
