### ISSUE TITLE
Alt tags?

### ISSUE THREAD

**Issue by errorcodezero** [natemoo-re/astro-icon#132]
Since these are svg icons I wonder if there is a way to specify a custom alt attribute for the icons.

**Comment by errorcodezero** [comment]
nvm I can just use aria-label on a tag

**Comment by stramel** [comment]
You can also use the `title` prop which inserts a `title` tag into the SVG

**Comment by errorcodezero** [comment]
oh alright

**Comment by errorcodezero** [comment]
thanks for the help 👍🏾

**Comment by kslstn** [comment]
AFAIK, the `alt` attribute is the correct way of providing a description for icons. As the element is an `<svg>`, it's [advisable](https://css-tricks.com/accessible-svgs/) to add `role="image"` too. The 'title' attribute is not helping users with screen readers much in this case. 

I successfully pass on both the 'role' and 'alt' attributes to `<Icon/>`, but `alt` gets a type error: 

```
Type '{ string?: string | number; children?: unknown; id?: string; type?: string; filter?: string; fill?: string; values?: string; path?: string; style?: string | Record<string, any>; width?: string | number; ... 396 more ...; alt: string; }' is not assignable to type 'IntrinsicAttributes & Props'.
  Property 'alt' does not exist on type 'IntrinsicAttributes & Props'.ts(2322)
```
