### ISSUE TITLE
Argument of type 'string | undefined' is not assignable to parameter of type 'string'

### ISSUE THREAD

**Issue by FDiskas** [natemoo-re/astro-icon#138]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `astro-icon@0.8.1` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/astro-icon/lib/createIconPack.ts b/node_modules/astro-icon/lib/createIconPack.ts
index c49ccae..3045d92 100644
--- a/node_modules/astro-icon/lib/createIconPack.ts
+++ b/node_modules/astro-icon/lib/createIconPack.ts
@@ -15,7 +15,7 @@ export function createIconPack({
 }: CreateIconPackOptions) {
   if (pkg) {
     return async (name: string) => {
-      const baseUrl = new URL(pathToFileURL(resolvePackage(pkg)) + "/");
+      const baseUrl = new URL(pathToFileURL(resolvePackage(pkg) ?? '') + "/");
       const path = fileURLToPath(
         new URL(dir ? `${dir}/${name}.svg` : `${name}.svg`, baseUrl)
       );
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by natemoo-re** [comment]
Thanks for the issue! I'm going to close this since [Astro Icon v1 has been released](https://www.astroicon.dev/guides/upgrade/v1/), but please open a new issue if you run into anything problems!
