### ISSUE TITLE
Icon displays in dev mode but not production

### ISSUE THREAD

**Issue by shriharip** [natemoo-re/astro-icon#158]
Hello,

I have an astro project which is deployed to cloudflare. 
It is in SSR mode.

I have an icon which diSplays in the dev mode, but during production it fails to display

Thanks in advance.

**Comment by natemoo-re** [comment]
Please make sure you've [upgraded to Astro Icon v1](https://www.astroicon.dev/guides/upgrade/v1/). There should be full support for deploying to Cloudflare in that version. If the issue is not solved, please open a new issue an include a reproduction.
