### ISSUE TITLE
Incorrect image sizes in the latest version (1.0.3)

### ISSUE THREAD

**Issue by spokospace** [natemoo-re/astro-icon#196]
### What version of `astro-icon` are you using?

v.1.0.3

### Astro Info

```block
❯ astro info
Astro                    v4.2.6
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             astro-icon
```

### Describe the Bug

In the latest version, all icons from @iconify-json are very large. I noticed that in svgs there is no width="1em" parameter, so svgs do not use font-based size.

In the previous version 1.0.2 everything worked fine, so I went back to this working version.

![image](https://github.com/natemoo-re/astro-icon/assets/16397823/7cd71e8b-6ce3-4ea9-8c32-329f29b76bcb)

### What's the expected result?

Display icons in normal size based on font like before.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-9w4guu?file=src%2Fpages%2Findex.astro

**Comment by natemoo-re** [comment]
Sorry about this! Looks like #186 had some unintended consequences. I'm reverting and 1.0.4 will be out shortly.
