### ISSUE TITLE
Failed to import SVG containing an <image> element

### ISSUE THREAD

**Issue by benruehl** [natemoo-re/astro-icon#206]
### What version of `astro-icon` are you using?

1.1.0

### Astro Info

```block
Astro                    v4.3.5
Node                     v18.18.0
System                   Linux (x64)
Package Manager          unknown
Output                   static
Adapter                  none
Integrations             astro-icon
```

### Describe the Bug

Upgraded a project from Astro 3.1.0 to 4.3.5 and astro-icon 0.8.0 to 1.1.0.

When I run `astro build` I get several errors with this pattern:

```shell
# astro build
Failed to import "filename": Unexpected element: <image>
```

When I run `astro dev` I get similar errors:

```shell
# astro dev
Unable to locate "filename" icon!
```

The respective files are SVG files that contain at least one `<image>` element. These image elements contain PNG data encoded as base64 which is totally valid SVG and was working fine before the upgrade.

It seems like it doesn't matter if and how the SVG files are imported. Their pure existence causes the error when astro-icon is installed.

### What's the expected result?

Build should run without errors when having SVG files with `<image>` elements in the `src` directory. Respective SVG files should be importable and usable as an image src, and should be found by the `<Icon>` component.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-ev9r7b?file=package.json

**Comment by smissaertj** [comment]
Did you find a workaround for this @natemoo-re ?

**Comment by RadoslavPavlinchov** [comment]
Any updates on this one?

**Comment by Sum112358** [comment]
This looks to be caused by @iconify/tools parsing methodology, In particular they explicitly don't declare <image> tags in https://github.com/iconify/tools/blob/main/%40iconify/tools/src/svg/data/tags.ts.

**Comment by stramel** [comment]
It appears so. This unfortunately is something we won't be able to fix in the current iteration. I believe the new experimental SVG inlining will handle this. 

For now, SVGs with an `image` tag should manually wrap rather than using this library.
