### ISSUE TITLE
depedency @iconify/tools v3 comes with incorrect types for cheerio (fixed in v4)

### ISSUE THREAD

**Issue by aripalo** [natemoo-re/astro-icon#210]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v4.4.11
Node                     v20.11.1
System                   macOS (arm64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/mdx
                         astro-icon
```

### Describe the Bug

Not directly a bug in `astro-icon`, but a bug that has been fixed in `astro-icon`'s depedencies.

[@iconify/tools](https://www.npmjs.com/package/@iconify/tools) had an [issue (that is fixed now)](https://github.com/iconify/tools/issues/35) where it installed `@type/cheerio` package even though `cheerio@1.0.0-rc.12` (which it uses) comes with its own (correct) type definitions.

You can see the transitive dependency of `@types/cheerio` in [astro-icon's `pnpm-lock.yaml`](https://github.com/natemoo-re/astro-icon/blob/a4ff8736965214e16ce0b72364f43b3a4973f281/pnpm-lock.yaml#L1261-L1263).

When using `cheerio@1.0.0-rc.12` in one's own codebase, this can lead to type errors as TypeScript is incorrectly resolving the types from `@types/cheerio` (and not the `cheerio` package itself).

I acknowledge that the fix would require a major version bump for `@iconify/tools` from v3 to v4, so this might require more work than just version bump, but I still feel this is an issue worth mentioning (and creating an issue for).

### What's the expected result?

We'll I'd like `astro-icon` to bump up its depedency of `@iconify/tools` from v3 to v4, so that one wouldn't have to deal with the incorrect `@types/cheerio`.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-8hrtln?file=src%2Fdemo.ts

**Comment by aripalo** [comment]
In case someone else has this problem, one **hacky**-workaround could be configuring this into `package.json`:
```js
"overrides": {
  "@iconify/tools": {
    "@types/cheerio": "https://registry.npmjs.org/cheerio/-/cheerio-1.0.0-rc.12.tgz"
    }
 },
```

Package.json [overrides](https://docs.npmjs.com/cli/v8/configuring-npm/package-json#overrides) allow to override the version of any dependency, but as npm accepts tgz url as version, I'm pointing it to the cheerio package instead.

**Comment by gianpaj** [comment]
This `package.json` works with `pnpm`:

```json
{
  "dependencies": {
    "astro-icon": "^1.1.0"
  },
  "pnpm": {
    "overrides": {
      "@iconify/tools": "^4.0.4"
    }
  }
}
```
