### ISSUE TITLE
Rendering Issue with Adjusted viewBox SVGs in astro-icon v1.1.0

### ISSUE THREAD

**Issue by tetracalibers** [natemoo-re/astro-icon#212]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v4.4.14
Node                     v20.4.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome, Safari, Firefox

### Describe the Bug

SVG icons adjusted with tools like [SVG Crop](https://svgcrop.com/) are partially missing when rendered using astro-icon v1.1.0. 

- [demo: sample site](https://tetracalibers.github.io/astro-icon-symbol-viewbox-test)

<img width="377" alt="スクリーンショット 2024-03-08 8 57 40" src="https://github.com/natemoo-re/astro-icon/assets/92695929/695ee8e5-c2f1-432b-8285-23e9b4c8a232">

The following situations do not cause problems:

- **Inline Icon Component**: Adding `is:inline` to the Icon component.
  - [demo: sample site](https://tetracalibers.github.io/astro-icon-symbol-viewbox-test/is-inline)
  - [demo: source code](https://github.com/tetracalibers/astro-icon-symbol-viewbox-test/blob/main/src/pages/is-inline.astro)

- **CSS Fix**: Adding `overflow: visible` to the symbol tag. 
  - [demo: sample site](https://tetracalibers.github.io/astro-icon-symbol-viewbox-test/symbol-overflow-visible)
  - [demo: source code](https://github.com/tetracalibers/astro-icon-symbol-viewbox-test/blob/main/src/pages/symbol-overflow-visible.astro)

### What's the expected result?

Removing the `viewBox` from `svg` elements and assigning it to the `symbol` element resolves the issue:

```html
<!-- Removed viewBox from svg element -->
<svg width="100" height="100" data-icon="astro-cropped">
  <!-- Instead, a viewBox is specified for the symbol element -->
  <symbol id="ai:local:astro-cropped" viewBox="4.93 2 22.15 28">
    <!-- ... -->
  </symbol>
  <use xlink:href="#ai:local:astro-cropped"></use>
</svg>

<!-- Removed viewBox from svg element -->
<svg width="100" height="100" data-icon="astro-cropped">
  <use xlink:href="#ai:local:astro-cropped"></use>
</svg>
```

### Link to Minimal Reproducible Example

https://github.com/tetracalibers/astro-icon-symbol-viewbox-test

**Comment by LushawnDev** [comment]
I'm getting a similar issue I think also due to viewbox. Currently investigating a fix for my case but intrigued to see follow up here.

**Comment by stramel** [comment]
Just added a PR for this. Sorry about that, this is fixed in our next iteration of astro-icon

**Comment by Razunter** [comment]
Maybe release it as beta if it's not fully ready yet?
