### ISSUE TITLE
Cannot change color of icon using styling

### ISSUE THREAD

**Issue by jamesmcl113** [natemoo-re/astro-icon#216]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v4.5.5
Node                     v21.7.1
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-icon
```

### If this issue only occurs in one browser, which browser is a problem?

Firefox

### Describe the Bug

I'm using the standard styling instructions but the color of the svg is not changing. I can see that the style is being applied using the inspector.

### What's the expected result?

The icon should change color.

### Link to Minimal Reproducible Example

https://github.com/natemoo-re/astro-icon?tab=readme-ov-file#styling

**Comment by bweis** [comment]
See #226 for details as to why this is.
