### ISSUE TITLE
feature: Disable optimized sprites

### ISSUE THREAD

**Issue by preetamslot** [natemoo-re/astro-icon#217]
### Astro Info

```block
latest
```

### Describe the Bug

When I use the same icon multiple times, but the first icon is in a vue component that transforms the icon, all icons are affected.

example. Social icons in a hidden menu, Now footer social icons only show when the menu is open (visible).

Arrow icon in faq, all icons rotate when the first faq item is open.

### What's the expected result?

I would like that the sprite is not affected by the state of the first icon OR that I can disable optimized sprites for an icon.

### Link to Minimal Reproducible Example

https://

**Comment by hrvstr** [comment]
This already possible with the `is:inline` directive.

https://github.com/natemoo-re/astro-icon/pull/200

**Comment by stramel** [comment]
I don't believe there are plans to implement this feature request. As mentioned above, we have `is:inline` that can disable the automatic sprite optimization. We may revisit this if there is more interest in a blanket flag for it.
