### ISSUE TITLE
How to make the icons be of same size as text?

### ISSUE THREAD

**Issue by schlichtanders** [natemoo-re/astro-icon#22]
I've tried using the astro-icon package, but found very huge icons appearing.

Is there a standard way to make the icons of the size of the text they stand next to?

**Comment by AndreBClark** [comment]
you can set styles/classes as attributes for the icons or use width/height attributes directly. you can use `rems` to size the icon relative to your base font size  which is `16px` by default or multiples of it
```astro
<div>
  <span style="font-size: 1rem">text</span>
  <Icon height="1rem">
</div>
```
hope this helps

**Comment by schlichtanders** [comment]
Thank you for the quick help.

I also looked into the source code and to the best of my understanding I would need to add the height information everywhere separately. That is too inconvenient for me unfortunately, but may work for others.
