### ISSUE TITLE
Automatically optimized sprites

### ISSUE THREAD

**Issue by J-env** [natemoo-re/astro-icon#223]
### What version of `astro-icon` are you using?

4.8.5

### Astro Info

```block
Astro                    v4.8.4
Node                     v18.18.0
System                   macOS (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             @astrojs/vue
```

### If this issue only occurs in one browser, which browser is a problem?

Chrome

### Describe the Bug

If the first svg `<symbol />` sprite is hidden, subsequent svg `<use />` will not be displayed.
```astro
// 
<div class="parent" style="display: none;">
  // first time
  <Icon name="logo" />
</div>

// Cannot be displayed here
<Icon name="logo" />

// ...
```

### What's the expected result?

This should be a problem with svg rendering itself. 

### Link to Minimal Reproducible Example

none

**Comment by stramel** [comment]
This is a quirk of the Sprite implementation that we chose to go with. You can switch these to inline for now using `is:inline`. We're working on a solution for the next iteration.
