### ISSUE TITLE
FATAL ERROR: Reached heap limit Allocation failed

### ISSUE THREAD

**Issue by AngeloThys** [natemoo-re/astro-icon#225]
### What version of `astro-icon` are you using?

v1.1.0

### Astro Info

```block
Astro                    v4.10.2
Node                     v18.20.1
System                   Linux (x64)
Package Manager          npm
Output                   static
Adapter                  none
Integrations             astro-icon
which: no xclip in [$PATH]
```

### Describe the Bug

When loading a page that contains an icon, the following happens:
 
astro  v4.10.2 ready in 284 ms

┃ Local    http://localhost:4321/
┃ Network  use --host to expose

17:36:44 watching for file changes...
17:36:46 [astro-icon] Loaded icons from fluent-emoji, logos, material-symbols-light

<--- Last few GCs --->

[218782:0x2eba9320]    21734 ms: Scavenge 4058.3 (4128.5) -> 4055.5 (4129.5) MB, 18.35
 / 0.00 ms  (average mu = 0.317, current mu = 0.145) allocation failure;
[218782:0x2eba9320]    21757 ms: Scavenge 4059.5 (4129.5) -> 4057.5 (4133.3) MB, 19.57
 / 0.00 ms  (average mu = 0.317, current mu = 0.145) allocation failure;
[218782:0x2eba9320]    21940 ms: Scavenge 4062.9 (4133.3) -> 4060.4 (4151.3) MB, 180.0
7 / 0.00 ms  (average mu = 0.317, current mu = 0.145) allocation failure;

<--- JS stacktrace --->

FATAL ERROR: Reached heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----

 1: 0xcd8bd6 node::OOMErrorHandler(char const*, v8::OOMDetails const&) [node]
 2: 0x10aed20 v8::Utils::ReportOOMFailure(v8::internal::Isolate*, char const*, v8::OOM
Details const&) [node]
 3: 0x10af007 v8::internal::V8::FatalProcessOutOfMemory(v8::internal::Isolate*, char c
onst*, v8::OOMDetails const&) [node]
 4: 0x12cdfe5  [node]
 5: 0x12e4b08  [node]
 6: 0x12bc00e v8::internal::HeapAllocator::AllocateRawWithLightRetrySlowPath(int, v8::
internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlig
nment) [node]
 7: 0x12bd2f4 v8::internal::HeapAllocator::AllocateRawWithRetryOrFailSlowPath(int, v8:
:internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAli
gnment) [node]
 8: 0x129afb5 v8::internal::Factory::NewFillerObject(int, v8::internal::AllocationAlig
nment, v8::internal::AllocationType, v8::internal::AllocationOrigin) [node]
 9: 0x16cb57c v8::internal::Runtime_AllocateInYoungGeneration(int, unsigned long*, v8:
:internal::Isolate*) [node]
10: 0x7c4923ca53f6
fish: Job 1, 'npm run dev' terminated by signal SIGABRT (Abort)

### What's the expected result?

The page loading with the chosen icon.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/withastro-astro-ufynmh?file=src%2Fpages%2Findex.astro,astro.config.mjs&title=Astro%20Starter%20Kit:%20Basics

**Comment by stramel** [comment]
I'm unable to reproduce this with the given stackblitz example. Caa you double-check or provide steps?

**Comment by OfficialCRUGG** [comment]
Not sure what else to provide as details for reproduction, but I am facing the same issue, also very explicitly when trying to use `fluent-emoji`. All other sets work fine. (well, most at least. I obviously haven't tried all)

My `astro info`:
```
Astro                    v5.5.5
Node                     v20.9.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             astro-icon
```
astro-icon is v1.1.5

**Update:** Out of curiosity, I've tried `fluent-emoji-flat` - all working here. It seems to very explicitly be only with the detailed fluent emojis. Perhaps it's something related to the file size / amount of detail in these files?

**Comment by stramel** [comment]
Interesting. Unless we can get a reproducible instance, this is very hard for us to determine the cause of. We do have a v2 coming out in the near future that should hopefully not have these issues. 

Though, I'm curious, can you try disabling SVGO through the `svgoOptions` config option?

**Comment by OfficialCRUGG** [comment]
@stramel I haven't quite found anything in the Documentation on completely disabling SVGO. I've tried setting `svgOptions` to false directly as well as settings `svgoOptions.multipass` to false. Is either of these what you meant?
In both cases, the problem still occurred.

**Comment by stramel** [comment]
> @stramel I haven't quite found anything in the Documentation on completely disabling SVGO. I've tried setting `svgOptions` to false directly as well as settings `svgoOptions.multipass` to false. Is either of these what you meant?
> In both cases, the problem still occurred.

Try setting plugins to an empty array, sorry it isn't very straightforward
