### ISSUE TITLE
Icon not showing (Symbol element missing from SVG) on Error pages 

### ISSUE THREAD

**Issue by JackMarksThomas** [natemoo-re/astro-icon#228]
### What version of `astro-icon` are you using?

"^1.1.0"

### Astro Info

```block
Astro                    v4.4.2
Node                     v18.19.0
System                   macOS (arm64)
Package Manager          npm
Output                   server
Adapter                  @astrojs/netlify
Integrations             @astrojs/tailwind
                         astro-icon
                         @astrojs/alpinejs
                         @sanity/astro
                         astro-robots-txt
                         astro-meta-tags
                         @sentry/astro
```

### If this issue only occurs in one browser, which browser is a problem?

All

### Describe the Bug

Astro icons works as expected on all pages, apart from Error pages (400, 500). On these pages I can see that the SVG element is added with the correct <use.../> tag, however the Symbol tag with the svg code inside is missing - as if the astro-icons has identified that it already exists somewhere on the page so can just reference it, but it obviously doesn't...

Interestingly it's working fine locally. And if I use `is:inline` directive it also works.

### What's the expected result?

The first time an icon is used it should render the symbol tag with the svg code, then if it is used again it can be referenced and symbol isn't required.

### Link to Minimal Reproducible Example

https://stackblitz.com/edit/github-3jmjzs?file=package.json&on=stackblitz

**Comment by dsijakovski98** [comment]
Same thing happens to me, but for all of the non-home pages.
Like "/" page has all icons available, but let's say "/about" page has some of the icons hidden for some reason.
Can't seem to figure out the issue

**Comment by kojimajunya** [comment]
The same issue is occurring, but I am having trouble because I don't know the conditions under which it happens.

**Comment by kojimajunya** [comment]
@dsijakovski98 
I also encountered a case where the <symbol> tag was not rendered. This occurred when I passed the <Icon> component using a slot in an island component (React component).

**Comment by stramel** [comment]
@JackMarksThomas I'm unable to reproduce using the stackblitz. Can you double-check and/or provide reproduction steps please? Will close until for now and re-open if it is able to be reproduced.

@dsijakovski98 If the Icon definition is hidden then it does break that icon and all references of it. This is a quirk of using the svg sprite the way we do. You can use the `is:inline` prop to force those icons to render.
