### ISSUE TITLE
Future maintenance? 

### ISSUE THREAD

**Issue by Nickersoft** [natemoo-re/astro-icon#229]
### What version of `astro-icon` are you using?

v1.0.0

### Astro Info

```block
Astro                    v4.13.2
Node                     v22.0.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   hybrid
Adapter                  @astrojs/cloudflare
Integrations             @astrojs/tailwind
                         @astrojs/mdx
```

### Describe the Bug

Apologies for using this template to not technically report a bug, but @natemoo-re – I saw you left Astro earlier this year. This is a fantastic plugin, and I was wondering what the future maintenance plans are? Could this be transferred to the official Astro org, or are there any other individuals looking to maintain it? 

I saw you hadn't committed in awhile, so I wasn't sure if you plan to continue supporting this package past your time with Astro.

### What's the expected result?

Hopefully, continued maintenance :( 

### Link to Minimal Reproducible Example

https://astro.build

**Comment by stramel** [comment]
Sorry for the lack of responses on here. The plan is to bring icons to the core Astro feature-set and then move this package into an Iconify extension of the core Astro feature. Then transfer to [Astrolicious](https://astrolicious.dev/) for more support .

**Comment by natemoo-re** [comment]
Correct, this package isn't going anywhere! I'm still committed to maintaining it and there are still plans to upstream some features to Astro.

While I did decide to move on from the Astro Technology Company, I'm still on Astro's core team and plan to remain involved on the open source side of things!

**Comment by Nickersoft** [comment]
Great to know @natemoo-re! Thanks :)
