### ISSUE TITLE
think about merging this effort with unplugin-icons

### ISSUE THREAD

**Issue by schlichtanders** [natemoo-re/astro-icon#23]
iconify is the go-to option for icons. It would be great to have a canonical way of using such items in astro.
To the best of my understanding, unplugin-icons would be the best place to create such canonical solution.

I already opened a feature request over there https://github.com/antfu/unplugin-icons/issues/154

How do you think about mergin `astro-icon` into `unplugin-icons`?

**Comment by stramel** [comment]
Thanks for suggesting this. I think this takes a slightly different approach and both can co-exist. 

I have added the Astro support for `unplugin-icons` upstream so both should work now.
