### ISSUE TITLE
Feature Request: add possibility to globally define parameters such as height

### ISSUE THREAD

**Issue by schlichtanders** [natemoo-re/astro-icon#24]
As seen in a separate issue, one cannot easily style the height for all icons to "1em".

At least for me, this global font scaling is very important, as I expect my fonts to just work and not need extra individual tweaking.

I am not sure whether it is possible, but if so, it would be nice to have some global options for this.

**Comment by ran-dall** [comment]
@schlichtanders, I believe you can use `[astro-icon]` in your project's root `.css` document to style all icons together. It also works with PostCSS in the pipeline too.

**Comment by schlichtanders** [comment]
thank you for your help.

can you give a concrete example css?

**Comment by ran-dall** [comment]
@schlichtanders Sure.

#### src/styles/style.css
```css
...
[astro-icon] {
	height: 6em;
}
...
```

**Comment by schlichtanders** [comment]
thank you very much.
Closing this issue then
