### ISSUE TITLE
What is it "highly recommended to include only the icons that are needed"?

### ISSUE THREAD

**Issue by kslstn** [natemoo-re/astro-icon#242]
### Astro Info

```block
n/a
```

### Describe the Bug

The docs say:

> When deploying an Astro site for server rendering, it is highly recommended to include only the icons that are needed.

I've got two questions about that.

1. Server rendering: does that mean server-side rendering, or general deployment including static rendering (SSG)?
2. I've not encountered issues while deploying an unrestricted icon set (SSG). As far as I can tell, astro-icon doesn't add any unnecessary data to the build, as it only adds inline SVGs and symbols to the HTML of icons that are actually used. Why is it recommended to only include icons that are needed?

Happy to contribute to the docs once I understand what this means.

### What's the expected result?

n/a

### Link to Minimal Reproducible Example

n/a

**Comment by stramel** [comment]
> Server rendering: does that mean server-side rendering, or general deployment including static rendering (SSG)?

Just SSR. Static generation  (SSG) is not included in that

> I've not encountered issues while deploying an unrestricted icon set (SSG). As far as I can tell, astro-icon doesn't add any unnecessary data to the build, as it only adds inline SVGs and symbols to the HTML of icons that are actually used. Why is it recommended to only include icons that are needed?

This is only an issue in the SSR as it will include every icon from each package you include. This can potentially lead to GBs worth of icons being installed on the server-side. These don't get shipped to the frontend though, just the ones you actually use.
