### ISSUE TITLE
Cannot mark an icon as optional and allow it to silently be omitted

### ISSUE THREAD

**Issue by dhruvkb** [natemoo-re/astro-icon#244]
### What version of `astro-icon` are you using?

1.1.1

### Astro Info

```block
Astro                    v4.16.2
Node                     v20.16.0
System                   macOS (arm64)
Package Manager          pnpm
Output                   static
Adapter                  none
Integrations             @astrojs/tailwind
                         @astrojs/mdx
                         watchPlugins
                         astro-icon
```

### Describe the Bug

I want to mark an icon as optional, i.e. the component should not raise an error if the icon does not exist in the `iconDir` directory. Currently if such an icon is referenced, the error takes over the whole page:

![image](https://github.com/user-attachments/assets/69ed0e75-8f05-4df7-a5d5-73c77656929c)

### What's the expected result?

The component should log the error but not take down the entire site like it does currently.

### Link to Minimal Reproducible Example

N/A

**Comment by stramel** [comment]
What's the use-case of an optional icon?

**Comment by dhruvkb** [comment]
I have icon names coming from an API where I want to supply some icons but let other icons be silently hidden.

**Comment by stramel** [comment]
After thinking about this further, I don't think this is something that we're interested in pursuing at this time. We're moving away from handling local files and going to be deferring this to Astro. This would make it pretty easy to do an implementation of this.

Checkout these 2 PRs, would love feedback/input.

- https://github.com/withastro/roadmap/pull/1035
- #239
