### ISSUE TITLE
Please add support for Flowbite icons

### ISSUE THREAD

**Issue by marceloverdijk** [natemoo-re/astro-icon#254]
### Astro Info

```block
N/A
```

### Describe the Bug

N/A

### What's the expected result?

N/A

### Link to Minimal Reproducible Example

.

**Comment by stramel** [comment]
This should be filed over in Iconify since we utilize them.

**Comment by marceloverdijk** [comment]
OK, I create a request at Iconify: https://github.com/iconify/iconify/issues/351

**Comment by marceloverdijk** [comment]
Apparently they are already available: https://icon-sets.iconify.design/flowbite/  💪
