### ISSUE TITLE
[Q] Use icon part of the bundle dynamically

### ISSUE THREAD

**Issue by marceloverdijk** [natemoo-re/astro-icon#255]
### What version of `astro-icon` are you using?

1.1.4

### Astro Info

```block
N/A
```

### Describe the Bug

Not a bug, but more a usage question.

I've included the Flag icon set using:

```
icon({
      include: {
        'flag': ['*'],
      },
    }),
```

Now in some places I use `<Icon name="flag:nl-4x3" />` which works as expected.

But I using dynamic tables (sorting + filtering), I need to render icons dynamically...
I'm outside Astro in that case so can't use the `<Icon />` component anymore, bit because of the `'flag': ['*']` inclusion every flag should be available in the bundle... is there a way to use them dynamically?

### What's the expected result?

Besides using the `<Icon />` component directly, also use the icons part of the bundle in a dynamic way.

### Link to Minimal Reproducible Example

*

**Comment by stramel** [comment]
Currently the only way to use the icons dynamically, would be to utilize the icon id. Though this isn't necessarily a public API so is likely to change in the next iteration of `astro-icon`. 

So you could do  `<svg><use href="#ai:flag:nl-4x3" /></svg>` as an example.
