### ISSUE TITLE
Bug: Sprite.Provider/Spritesheet breaks pages where sprites are not used 

### ISSUE THREAD

**Issue by btk5h** [natemoo-re/astro-icon#28]
`Sprite.Provider` breaks pages that do not use any sprites.

## Steps to reproduce
Create an astro page with a `Sprite.Provider` but with no `Sprite` components as children

## Observed behavior
The page fails to build with a misleading "\<SpriteSheet\> should be the very last child of the page's \<body\>!" error

## Desired behavior
The page builds and renders properly

## Workaround
Don't render the `Sprite.Provider` on pages (which may be difficult if placed in a layout component), or add a hidden sprite to each page

**Comment by natemoo-re** [comment]
Ah this is a good point, I think I can remove this behavior now. This was mostly to catch issues when migrating.

**Comment by natemoo-re** [comment]
Fixed this in https://github.com/natemoo-re/astro-icon/commit/3b29d893bbb385c8e6e8fa51b421fefa17b050ac and released in `astro-icon@0.7.0`!
