### ISSUE TITLE
Add `title` inside `svg` to improve accessibility

### ISSUE THREAD

**Issue by ownchoice** [natemoo-re/astro-icon#36]
I think it would be nice to be able to add a `title` tag inside the `svg` of the icon, for accessibility purposes.

```html
<svg role="img"><title>Good Label</title> ... </svg>.
```

For reference: [Accessible SVG Icons | CSS-Tricks](https://css-tricks.com/accessible-svg-icons/)

**Comment by m4rrc0** [comment]
I was just looking for the exact same thing and discovered there is a `title` prop for that. 🤩
See [Props.ts](https://github.com/natemoo-re/astro-icon/blob/main/packages/core/lib/Props.ts) for all the props available.
