### ISSUE TITLE
Use in non-astro components?

### ISSUE THREAD

**Issue by silveltman** [natemoo-re/astro-icon#41]
Can this be used in components other than .astro? Like .svelte, .vue etc.

I'm getting an error but not sure what the exact reason for this is

**Comment by yacosta738** [comment]
Hi, I am interested in use in other components. Is that possible?

**Comment by kissu** [comment]
I guess that we could use https://github.com/antfu/unplugin-icons for the other languages but it's indeed a bit counter-productive to need to have both.

**Comment by stramel** [comment]
You can use the `Icon` component in other framework components by utilizing the `<slot />` feature. 

https://docs.astro.build/en/core-concepts/framework-components/#can-i-use-astro-components-inside-my-framework-components

**Comment by kissu** [comment]
I will need to give that one a try!

**Comment by stramel** [comment]
Going to close this since this is possible. Feel free to comment if you're experiencing issues.

**Comment by wpplumber** [comment]
Welcome, is there a Vue sample?

**Comment by Corentin7301** [comment]
@wpplumber Do you have find an example with Vue 3?
I've the following problem:
| index.astro
| components
  | Slider.vue
  | Card.vue
  
I use a v-for in Slider and send data of card by props to card.
In this card, I would like to add icons but I don't find a solution for that...

**Comment by wpplumber** [comment]
Welcome @Corentin7301, I use [unplugin](https://github.com/antfu/unplugin-icons) now. 💪
