### ISSUE TITLE
Icon not found

### ISSUE THREAD

**Issue by lyqht** [natemoo-re/astro-icon#48]
Got the following error

```
Error: Not Found: "newspaper" in pack "charm"
    at request (/node_modules/astro-icon/lib/resolver.ts:17:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

However, I've checked from the charm icon pack that [it exists](https://icon-sets.iconify.design/charm/newspaper/).

**Comment by manuelmeister** [comment]
This probably has to do with #29

**Comment by stramel** [comment]
Yep, duplicate of #29
