### ISSUE TITLE
Heroicons not found?

### ISSUE THREAD

**Issue by richcorbs** [natemoo-re/astro-icon#51]
Looks like `https://api.astroicon.dev/v1/heroicons/<anything>` returns `Not Found: Pack "heroicons"`.

Maybe it has to do with their release of heroicons v2 this week?

**Comment by coding-in-public** [comment]
Looks like they've fixed it? @richcorbs

It was probably from the Iconify api?

**Comment by richcorbs** [comment]
I'm still seeing the same thing. I've tried:

- https://api.astroicon.dev/v1/heroicons/menu
- https://api.astroicon.dev/v1/heroicons/bars-3

It still gives me the "pack not found" error.

Are you seeing it working?

**Comment by richcorbs** [comment]
So `heroicons-outline/menu` worked. This is probably user error?

**Comment by caincodes** [comment]
I'm having the same issue. `heroicons-outline` works, but that's not heroicons v2, and v1 is considered archived/unmaintained by Iconify, so this should probably be updated if that's the issue.
