### ISSUE TITLE
Invalid HTML due to astro-icon attribute

### ISSUE THREAD

**Issue by Coretteket** [natemoo-re/astro-icon#55]
Custom attributes without the `data-` prefix are non-standard, and disfavored by validators like [Nu Html Checker](https://validator.w3.org/nu/) (see below). It would be a breaking change, but replacing `astro-icon` with `data-astro-icon` (or `data-icon`) would be an improvement.

![afbeelding](https://user-images.githubusercontent.com/33397397/192524577-e439d7b8-f6ca-4470-987c-85e5d79b02bf.png)

**Comment by stramel** [comment]
I think we can supply both until we're ready for a breaking change.

**Comment by Janssenhidal** [comment]
Are there any updates regarding this issue? Is this something that's going to be fixed in the near future?

Thanks

**Comment by stramel** [comment]
@Janssenhidal I'm working on a path forward for `astro-icon` currently. I will see if I can squeeze this in the current planned release.

**Comment by stramel** [comment]
@Janssenhidal I'm working on a plan forward with `astro-icon`. 

Taking a step back and looking at this request, there isn't an actual issue with the existing code. This comes down to the validator being very strict conformance to the HTML spec. You can find more discussions here:
https://github.com/whatwg/html/issues/2271
https://github.com/validator/validator/issues/488

So I think until this is resolved, we will continue forward with the `astro-icon` attribute as this follows the current practices from modern frameworks. There _might_ be opportunity after some of the refactors land to expose a custom attribute configuration where you could override the `astro-icon` attribute to `data-astro-icon`.
