### ISSUE TITLE
Google Material Symbols not Found

### ISSUE THREAD

**Issue by HritikR** [natemoo-re/astro-icon#60]
Code :  `<Icon name="material-symbols:10k"  />`

```
Error: Not Found: pack "material-symbols"
    at request (/node_modules/astro-icon/lib/resolver.ts:17:13)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by Nikola-Milovic** [comment]
How did you resolve this? Is there some shorthand name or something?

**Comment by HritikR** [comment]
The Astro-Icon API lacks a large number of icon packs because they have been using old version of iconify.
I had to develop my own API which uses latest version of Iconify. I created the API and integrated it into fork of Astro-icon.

**Comment by ChrisChinchilla** [comment]
@HritikR and @manuelmeister I started using the iconify fork, but there's no issue tracker there… That fork seems to be affected by this issue https://github.com/natemoo-re/astro-icon/issues/65 and I couldn't get the workaround to work, any ideas?
