### ISSUE TITLE
typescript Props tips?

### ISSUE THREAD

**Issue by J-env** [natemoo-re/astro-icon#62]
Component has no props tips

**Comment by stramel** [comment]
@J-env Can you provide more information? I'm able to see the Prop tips in VSCode when using this package.

**Comment by stramel** [comment]
I'm going to close this for now. I'm willing to re-open if more details are provided and proves to be an issue with the library.

**Comment by benjavicente** [comment]
Hi and thanks for the awesome library!

I have the same problem in version `0.8.0`: The `Icon` component gives me the following type:
 
```ts.d
function Icon(_props: Record<string, any>): any
```

Initializing an empty project and using the `Icon` component like

```astro
<Icon thisShouldGiveAnError="here" />
```

doesn't give an error while type checking with `astro check`.

Installing the library with `pnpm` or `npm` made no diference.
