### ISSUE TITLE
`heroicons:user` is not loading showing a blank box

### ISSUE THREAD

**Issue by sacarvy** [natemoo-re/astro-icon#70]
Might be there is some APIs changes needed to make it work.

Currently it's just `heroicons:user` not working, Hope you got some time to check into the issue.

Hope it helps to work with newer packages, thanks for such a great package.

**Comment by sacarvy** [comment]
https://icones.js.org/collection/all?s=heroicons:user quick link to find the icon which is not loading, you can try any heroicons It's not working for all, I find it now!

**Comment by surjithctly** [comment]
None of the heroicons and many icons shown in `icones` are not loaded, but showing a big box. It would be great if its included by default or added an easy import option.

**Comment by mfazail** [comment]
Same here 😑, trying to load `heroicons:check-badge` and its shows 
`Error: Not Found: pack "heroicons"` in terminal.

**Comment by vfxjohow** [comment]
Hey there! 

Also have issues with some icons. Looks like some icons of the line-md pack are not loading properly. 

In example: line-md:moon-alt-to-sunny-outline-loop-transition

The package idea is great thank you for that!

**Comment by surjithctly** [comment]
I guess its mostly because of this outdated plugin used. See: https://github.com/natemoo-re/astro-icon/issues/73

**Comment by liv3rise** [comment]
same with fluent emoji pack 🙁

**Comment by stramel** [comment]
The blank box is the fallback icon built-in to the plugin. I think this should be a bit more clear in the documentation or icon rendered.

As far as the mission icons go, that would be due to #29.
