### ISSUE TITLE
Upgrade to @iconify/utils because @iconify/json-tools is depreciated

### ISSUE THREAD

**Issue by surjithctly** [natemoo-re/astro-icon#73]
Upgrade to [@iconify/utils](https://www.npmjs.com/package/@iconify/utils) because [@iconify/json-tools](https://www.npmjs.com/package/@iconify/json-tools) is depreciated on npm and no longer recommended. Not updated in last two years. This causes so many bugs in the plugin itself. I guess most issues will be fixed once upgraded. 

<img width="570" alt="CleanShot 2022-12-18 at 18 42 50@2x" src="https://user-images.githubusercontent.com/1884712/208300323-278cb7be-ee03-419f-8415-9ce4af6f16c4.png">

**Comment by Pukimaa** [comment]
@natemoo-re told me he would wanted to fix that. But nothing has happened since sadly. If I remember correctly he also talked about making this repo an official astro repo. I don't know how far they're with the plan. But it would be something I would be looking forward as well.

**Comment by surjithctly** [comment]
Making this an official implementation would be a great idea indeed considering its popularity.

**Comment by stramel** [comment]
Yes, this is something that we're intending to address in the next major release. I think once we get the next major release out we can discuss bringing it into the official package.

**Comment by stramel** [comment]
This will be covered under the v1 rework. #87
