### ISSUE TITLE
Page doesn't load when using astro-icons with ssr

### ISSUE THREAD

**Issue by PringlePot** [natemoo-re/astro-icon#77]
After some trying, it seems like using the `@astrojs/node` build output does not work with astro-icon. It causes the page to be stuck at loading when in a production build. It does work in normal `yarn dev` mode tho. There are no errors in the console while building or running the code with `yarn preview` which makes it hard to debug the issue and find the root of the problem

**Comment by aaronteamAAR** [comment]
> After some trying, it seems like using the `@astrojs/node` build output does not work with astro-icon. It causes the page to be stuck at loading when in a production build. It does work in normal `yarn dev` mode tho. There are no errors in the console while building or running the code with `yarn preview` which makes it hard to debug the issue and find the root of the problem

So do suggest using yarn over npm while using astro-icon ?

**Comment by stramel** [comment]
There is a known limitation with SSR currently when using this plugin. See #35. Please feel free to provide more information if you're running into a different issue than the existing SSR limitations.

**Comment by PringlePot** [comment]
The issue is, I'm using nodejs to host the server, so svgo should work right?
