### ISSUE TITLE
Getting a big black square when using local icons

### ISSUE THREAD

**Issue by ameneses67** [natemoo-re/astro-icon#84]
I put some icons on src/icons/ but when I call them <Icon name="example" /> I just get a big black square. Tried using different svs's but no luck.

**Comment by stramel** [comment]
The black square is a hardcoded fallback for when the icon isn't found. This will be addressed through better error messaging in the v1 branch.  However, for your current setup you will need to post some more information if you're looking for help on resolving your icons.
