### ISSUE TITLE
Feature Request: option to normalize CSS & IDs

### ISSUE THREAD

**Issue by drwpow** [natemoo-re/astro-icon#9]
## Problem

Many icons are optimized using [SVGO](https://github.com/svg/svgo) which is very good at compression! But the side effect is that it will minify classes and IDs, like so:

```html
<svg><style>.a{fill:#fc6d26}</style><path class="a" d="…
<svg><defs><linearGradient id="a">…
```

Even if icons aren’t optimized with SVGO at all, there’s still a really good chance of class & ID conflicts if a sprite sheet is big enough (`id="Layer_1"` is suspect). Any conflict at all will likely mean the icon displays incorrectly.

## API

Unsure about the API (should this be default behavior? configurable? dunno!)

## Solution A

One solution would be to inline `<style>`s, e.g. (which is an SVGO setting, I believe):

```diff
- <svg><style>.a{fill:#fc6d26}</style><path class="a" d="…
+ <svg><path fill="#fc6d26" d="…">
```

But that still leaves IDs!

## Solution B

Probably a better solution is to not transform anything, but simply prefix all classes and IDs within an SVG, e.g.:

```html
<svg><style>.astroicon-icon-github-a{fill:#fc6d26}</style><path class="a" d="…
<svg><defs><linearGradient id="astroicon-icon-github-a">…
```

(prefix can match the SVG IDs; not important)

## Other

- [x] I am willing to create a PR for this

**Comment by natemoo-re** [comment]
Yeah I like this idea a lot, I'm also bitten by this frequently!

For reference if you end up digging into this, we already have a [`preprocess` function](https://github.com/natemoo-re/astro-icon/blob/main/packages/core/lib/utils.ts#L69-L94) that could be extended with this behavior.

**Comment by natemoo-re** [comment]
Actually, I did a lil digging and `svgo` already has this feature built-in! I just don't think many other tools have use for it, but we sure do.

Will be adding this in a patch release. ☺️

**Comment by natemoo-re** [comment]
`itshappening.gif`

https://github.com/natemoo-re/astro-icon/commit/0217a716c7278e30a04de45f72e7a3cce5c65180
