### ISSUE TITLE
Will icons be used in framework components?

### ISSUE THREAD

**Issue by recallwei** [natemoo-re/astro-icon#92]
I want to use icons in framework components (React or Vue).
Currently seems not to support.

**Comment by recallwei** [comment]
Currently, Astro components can be passed through slots. Is it possible to use them directly in framework components?

**Comment by stramel** [comment]
It is not possible to use `astro-icon` directly in other framework components. You can use them inside framework components using slots. 

Will work to add documentation around this.

Closing this as a duplicate of #41
